name: flutter_twitter_login
description: A Flutter plugin for allowing users to authenticate with native Android &amp; iOS Twitter login SDKs.
version: 1.0.1
author: Iiro Krankka <iiro.krankka@gmail.com>
homepage: https://github.com/roughike/flutter_twitter_login

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.roughike.fluttertwitterlogin.fluttertwitterlogin
    pluginClass: TwitterLoginPlugin

environment:
    sdk: ">=1.8.0 <2.0.0"