name: flutter_twitter_ab
description: A Flutter plugin for allowing users to authenticate with native Android &amp; iOS Twitter login SDKs.
version: 1.1.1
author: Andrii Bodnar <a.bodnarrr@gmail.com>
homepage: https://github.com/bodnarrr/flutter_twitter_login

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.bodnarrr.fluttertwitterab.fluttertwitterab
    pluginClass: TwitterLoginPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"